query Category($handle: MetaobjectHandleInput!) {
  category: metaobject(handle: $handle) {
    id
    handle
    title: field(key: "title") {
      value
    }
    name: field(key: "name") {
      value
    }
    content: field(key: "content") {
      value
    }
    seo {
      title {
        value
      }
      description {
        value
      }
    }
  }
}
