mutation CartLinesUpdate($cartId: ID!, $lines: [CartLineUpdateInput!]!) {
  cartLinesUpdate(cartId: $cartId, lines: $lines) {
    cart {
      ...CartFragment @mask_disable
    }
    userErrors {
      ...CartUserErrorFragment @mask_disable
    }
  }
}
